from decouple import config
from datetime import timedelta

DATABASE_URL = config('DATABASE_URL')
SECRET_KEY = config('SECRET_KEY')
ALGORITHM = config('ALGORITHM', default='HS256')
ACCESS_TOKEN_EXPIRE_MINUTES = config('ACCESS_TOKEN_EXPIRE_MINUTES', default=30, cast=int)
REFRESH_TOKEN_EXPIRE_DAYS = 7

BEDROCK_MODEL_CLAUDE_INSTANT=config('BEDROCK_MODEL_CLAUDE_INSTANT')
BEDROCK_MODEL_TITAN_TEXT=config('BEDROCK_MODEL_TITAN_TEXT')
BEDROCK_MODEL_EMBEDDING=config('BEDROCK_MODEL_EMBEDDING')

S3_BUCKET_NAME=config('S3_BUCKET_NAME')

ACCESS_TOKEN_EXPIRE_TIMEDELTA = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
REFRESH_TOKEN_EXPIRE_TIMEDELTA = timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)

PINECONE_API_KEY = config("PINECONE_API_KEY")
PINECONE_INDEX_NAME = config("PINECONE_INDEX_NAME")